
version: 2

sources:
    - name: staging
      #For bigquery:
      database: de-project-375820

      # For postgres:
      #database: production

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata_partitoned_clustered
        - name: yellow_tripdata_non_partitoned
         # freshness:
           # error_after: {count: 6, period: hour}